# Disable Esc from quitting â€” only quit with q
[[mgr.prepend_keymap]]
on = [ "<Esc>" ]
run = "noop"
desc = "Do nothing"

[[mgr.prepend_keymap]]
on = [ "q" ]
run = "noop"
desc = "Disable single q quit"

[[mgr.prepend_keymap]]
on = [ "q", "q" ]
run = "quit"
desc = "Quit yazi"

[[mgr.prepend_keymap]]
on = [ "g", "c" ]
run = "cd ~/.dotfiles"
desc = "Goto ~/.dotfiles"

# https://github.com/Lil-Dank/lazygit.yazi
[[mgr.prepend_keymap]]
on   = [ "g", "l" ]
run  = "plugin lazygit"
desc = "run lazygit"

# [[manager.prepend_keymap]]
# on   = "f"
# run  = "plugin jump-to-char"
# desc = "Jump to char"
